<?xml version='1.1' encoding='UTF-8'?>
<build>
  <actions>
    <hudson.model.ParametersAction>
      <safeParameters class="sorted-set"/>
      <parameters>
        <hudson.model.StringParameterValue>
          <name>GITHUB_NAME</name>
          <description>GitHub repository owner/repo_name (e.g.: &quot;EpitechPGE2-2025/G-OOP-400-MAR-4-1-tekspice-23&quot;)</description>
          <value>EpitechPGE2-2025/G-OOP-400-MAR-4-1-arcade-6</value>
        </hudson.model.StringParameterValue>
        <hudson.model.StringParameterValue>
          <name>DISPLAY_NAME</name>
          <description>Display name for the job</description>
          <value>arcade</value>
        </hudson.model.StringParameterValue>
      </parameters>
      <parameterDefinitionNames>
        <string>GITHUB_NAME</string>
        <string>DISPLAY_NAME</string>
      </parameterDefinitionNames>
    </hudson.model.ParametersAction>
    <hudson.model.CauseAction>
      <causeBag class="linked-hash-map">
        <entry>
          <hudson.model.Cause_-UserIdCause>
            <userId>chocolateen</userId>
          </hudson.model.Cause_-UserIdCause>
          <int>1</int>
        </entry>
      </causeBag>
    </hudson.model.CauseAction>
  </actions>
  <queueId>5</queueId>
  <timestamp>1776099935961</timestamp>
  <startTime>1776099936033</startTime>
  <result>FAILURE</result>
  <duration>780</duration>
  <charset>UTF-8</charset>
  <keepLog>false</keepLog>
  <builtOn></builtOn>
  <workspace>/var/jenkins_home/jobs/tools/jobs/SEED/workspace</workspace>
  <hudsonVersion>2.541.3</hudsonVersion>
  <scm class="hudson.scm.NullChangeLogParser"/>
  <culprits class="java.util.Collections$UnmodifiableSet">
    <c class="sorted-set"/>
  </culprits>
</build>