def githubName = binding.hasVariable('GITHUB_NAME') ? GITHUB_NAME : System.getenv('GITHUB_NAME')
def displayName = binding.hasVariable('DISPLAY_NAME') ? DISPLAY_NAME : System.getenv('DISPLAY_NAME')

if (!githubName?.trim()) {
    throw new IllegalArgumentException('GITHUB_NAME is required')
}
if (!displayName?.trim()) {
    throw new IllegalArgumentException('DISPLAY_NAME is required')
}

job(displayName) {
    description("Generated by SEED for ${githubName}")

    properties {
        githubProjectUrl("https://github.com/${githubName}")
    }

    scm {
        git {
            remote {
                github(githubName, 'https')
            }
        }
    }

    triggers {
        scm('* * * * *')
    }

    wrappers {
        preBuildCleanup()
    }

    steps {
        shell('make fclean')
        shell('make')
        shell('make tests_run')
        shell('make clean')
    }
}
